# Generated by Django 5.1.4 on 2025-08-05 02:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mail',
            field=models.EmailField(blank=True, max_length=55, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
