# Generated by Django 5.1.4 on 2025-08-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_mail_todo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='mail',
            new_name='email',
        ),
    ]
