# Generated by Django 5.1.4 on 2025-08-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_mail_todo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='email',
            field=models.EmailField(blank=True, max_length=55, null=True),
        ),
    ]
