# Generated by Django 5.1.4 on 2025-08-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
