# Generated by Django 5.1.4 on 2025-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
