# Generated by Django 5.1.4 on 2025-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
